name: audio_analyzer
description: "Analyze audio files"
version: 0.0.3
homepage: https://github.com/YofarDev/audio_analyzer

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: fr.yofardev.audio_analyzer
        pluginClass: AudioAnalyzerPlugin
      ios:
        pluginClass: AudioAnalyzerPlugin
      web:
        pluginClass: AudioAnalyzerWeb
        fileName: audio_analyzer_web.dart
      macos:
        pluginClass: AudioAnalyzerPlugin
        
